# Auto-generated by release workflow. Do not edit manually.
class Jl < Formula
  desc "A JSON log pretty-printer"
  homepage "https://github.com/genuss/jl"
  license "MIT"
  version "0.0.1-rc1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/genuss/jl/releases/download/v0.0.1-rc1/jl-v0.0.1-rc1-aarch64-apple-darwin.tar.gz"
      sha256 "cdf9ce19be257d26df8fd904c2c00e23eacc2519bb8cf275d957dfb52914b464"
    else
      url "https://github.com/genuss/jl/releases/download/v0.0.1-rc1/jl-v0.0.1-rc1-x86_64-apple-darwin.tar.gz"
      sha256 "a3be1d2c7040f0ba05966e0bc7b334f3ff6f618fa5193a67498fbf9735469009"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/genuss/jl/releases/download/v0.0.1-rc1/jl-v0.0.1-rc1-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "0fdacd465657205c2c616f8d5e904e8f1fb2efa302e1e3e7c0cd5fb6712365d5"
    else
      url "https://github.com/genuss/jl/releases/download/v0.0.1-rc1/jl-v0.0.1-rc1-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "6b55d6e784f800b352f42f7db0a17af25b15f7f84e6391c08b5f78c0a8a4a358"
    end
  end

  def install
    bin.install "jl"
    generate_completions_from_executable(bin/"jl", "--completions")
  end

  test do
    pipe_output("#{bin}/jl", '{"message":"hello"}', 0)
  end
end
